stages:
  ingest:
    cmd: python scripts/get_and_save_data.py
    deps:
    - data/raw
    - scripts/get_and_save_data.py
    outs:
    - data/interim/all_immo_entries.csv
  drop_empty:
    cmd: python scripts/delete_empty_data.py
    deps:
    - data/interim/all_immo_entries.csv
    - scripts/delete_empty_data.py
    outs:
    - data/interim/all_immo_no_empty.csv
  features:
    cmd: python scripts/clean_and_prepare_data.py
    deps:
    - data/interim/all_immo_no_empty.csv
    - scripts/clean_and_prepare_data.py
    outs:
    - data/processed/features_immo_data.csv
  train:
    cmd: python scripts/train.py
    deps:
    - data/processed/features_immo_data.csv
    - scripts/train.py
    outs:
    - artefacts/Model_prix_dvf.joblib
