# ═══════════════════════════════════════════════════════════════════════════════
# PROMETHEUS CONFIGURATION - Collecte de métriques MLOps

# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION GLOBALE
# ─────────────────────────────────────────────────────────────────────────────
global:
  scrape_interval: 15s
  
# ═══════════════════════════════════════════════════════════════════════════
# SCRAPE CONFIGS - Définition des targets à monitorer
# ═══════════════════════════════════════════════════════════════════════════
scrape_configs:
  
  # ─────────────────────────────────────────────────────────────────────────
  # JOB 1 : Application FastAPI (métriques métier)
  # ─────────────────────────────────────────────────────────────────────────
  - job_name: 'immo_app_g1'    
    static_configs:
      - targets: ['cv_app:8000']    
    metrics_path: '/metrics'    
    scrape_interval: 10s
    

  # ─────────────────────────────────────────────────────────────────────────
  #  JOB 2 : Auto-monitoring Prometheus
  # ─────────────────────────────────────────────────────────────────────────
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:50001']
       